services:
  - type: web
    name: dexmap-technologys-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false

  - type: web
    name: dexmap-technologys-site
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./client/dist
    envVars:
      - key: VITE_API_URL
        sync: false
